// Code generated by MockGen. DO NOT EDIT.
// Source: postgres.go
//
// Generated by this command:
//
//	mockgen -source=postgres.go -destination=mocks/mock_db.go -package=mocks DB
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/amin-mir/enma/internal/model"
	postgres "github.com/amin-mir/enma/internal/postgres"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockDB is a mock of DB interface.
type MockDB struct {
	ctrl     *gomock.Controller
	recorder *MockDBMockRecorder
	isgomock struct{}
}

// MockDBMockRecorder is the mock recorder for MockDB.
type MockDBMockRecorder struct {
	mock *MockDB
}

// NewMockDB creates a new mock instance.
func NewMockDB(ctrl *gomock.Controller) *MockDB {
	mock := &MockDB{ctrl: ctrl}
	mock.recorder = &MockDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDB) EXPECT() *MockDBMockRecorder {
	return m.recorder
}

// CreateJournalEntry mocks base method.
func (m *MockDB) CreateJournalEntry(ctx context.Context, userID uuid.UUID, content string) (postgres.CreateJournalEntryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateJournalEntry", ctx, userID, content)
	ret0, _ := ret[0].(postgres.CreateJournalEntryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateJournalEntry indicates an expected call of CreateJournalEntry.
func (mr *MockDBMockRecorder) CreateJournalEntry(ctx, userID, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateJournalEntry", reflect.TypeOf((*MockDB)(nil).CreateJournalEntry), ctx, userID, content)
}

// CreateRefreshToken mocks base method.
func (m *MockDB) CreateRefreshToken(ctx context.Context, userID uuid.UUID, tokenHash string, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRefreshToken", ctx, userID, tokenHash, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRefreshToken indicates an expected call of CreateRefreshToken.
func (mr *MockDBMockRecorder) CreateRefreshToken(ctx, userID, tokenHash, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRefreshToken", reflect.TypeOf((*MockDB)(nil).CreateRefreshToken), ctx, userID, tokenHash, expiresAt)
}

// CreateUser mocks base method.
func (m *MockDB) CreateUser(ctx context.Context, email, hash string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, email, hash)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockDBMockRecorder) CreateUser(ctx, email, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockDB)(nil).CreateUser), ctx, email, hash)
}

// DeleteRefreshTokenByHash mocks base method.
func (m *MockDB) DeleteRefreshTokenByHash(ctx context.Context, tokenHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRefreshTokenByHash", ctx, tokenHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRefreshTokenByHash indicates an expected call of DeleteRefreshTokenByHash.
func (mr *MockDBMockRecorder) DeleteRefreshTokenByHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRefreshTokenByHash", reflect.TypeOf((*MockDB)(nil).DeleteRefreshTokenByHash), ctx, tokenHash)
}

// GetJournalEntry mocks base method.
func (m *MockDB) GetJournalEntry(ctx context.Context, entryID, userID uuid.UUID) (model.JournalEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJournalEntry", ctx, entryID, userID)
	ret0, _ := ret[0].(model.JournalEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJournalEntry indicates an expected call of GetJournalEntry.
func (mr *MockDBMockRecorder) GetJournalEntry(ctx, entryID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJournalEntry", reflect.TypeOf((*MockDB)(nil).GetJournalEntry), ctx, entryID, userID)
}

// GetUserByEmail mocks base method.
func (m *MockDB) GetUserByEmail(ctx context.Context, email string) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockDBMockRecorder) GetUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockDB)(nil).GetUserByEmail), ctx, email)
}

// ListJournalEntries mocks base method.
func (m *MockDB) ListJournalEntries(ctx context.Context, userID uuid.UUID) ([]model.JournalEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListJournalEntries", ctx, userID)
	ret0, _ := ret[0].([]model.JournalEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListJournalEntries indicates an expected call of ListJournalEntries.
func (mr *MockDBMockRecorder) ListJournalEntries(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListJournalEntries", reflect.TypeOf((*MockDB)(nil).ListJournalEntries), ctx, userID)
}

// RotateRefreshToken mocks base method.
func (m *MockDB) RotateRefreshToken(ctx context.Context, oldTokenHash, newTokenHash string, expiresAt time.Time) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RotateRefreshToken", ctx, oldTokenHash, newTokenHash, expiresAt)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RotateRefreshToken indicates an expected call of RotateRefreshToken.
func (mr *MockDBMockRecorder) RotateRefreshToken(ctx, oldTokenHash, newTokenHash, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RotateRefreshToken", reflect.TypeOf((*MockDB)(nil).RotateRefreshToken), ctx, oldTokenHash, newTokenHash, expiresAt)
}

// UpdateJournalEntry mocks base method.
func (m *MockDB) UpdateJournalEntry(ctx context.Context, entryID, userID uuid.UUID, content string, version int32) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateJournalEntry", ctx, entryID, userID, content, version)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateJournalEntry indicates an expected call of UpdateJournalEntry.
func (mr *MockDBMockRecorder) UpdateJournalEntry(ctx, entryID, userID, content, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateJournalEntry", reflect.TypeOf((*MockDB)(nil).UpdateJournalEntry), ctx, entryID, userID, content, version)
}
