// Code generated by MockGen. DO NOT EDIT.
// Source: journal.go
//
// Generated by this command:
//
//	mockgen -source=journal.go -destination=mocks/mock_journal.go -package=mocks JournalService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/amin-mir/enma/internal/model"
	postgres "github.com/amin-mir/enma/internal/postgres"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockJournalService is a mock of JournalService interface.
type MockJournalService struct {
	ctrl     *gomock.Controller
	recorder *MockJournalServiceMockRecorder
	isgomock struct{}
}

// MockJournalServiceMockRecorder is the mock recorder for MockJournalService.
type MockJournalServiceMockRecorder struct {
	mock *MockJournalService
}

// NewMockJournalService creates a new mock instance.
func NewMockJournalService(ctrl *gomock.Controller) *MockJournalService {
	mock := &MockJournalService{ctrl: ctrl}
	mock.recorder = &MockJournalServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJournalService) EXPECT() *MockJournalServiceMockRecorder {
	return m.recorder
}

// CreateJournalEntry mocks base method.
func (m *MockJournalService) CreateJournalEntry(ctx context.Context, userID uuid.UUID, content string) (postgres.CreateJournalEntryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateJournalEntry", ctx, userID, content)
	ret0, _ := ret[0].(postgres.CreateJournalEntryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateJournalEntry indicates an expected call of CreateJournalEntry.
func (mr *MockJournalServiceMockRecorder) CreateJournalEntry(ctx, userID, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateJournalEntry", reflect.TypeOf((*MockJournalService)(nil).CreateJournalEntry), ctx, userID, content)
}

// GetJournalEntry mocks base method.
func (m *MockJournalService) GetJournalEntry(ctx context.Context, entryID, userID uuid.UUID) (model.JournalEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJournalEntry", ctx, entryID, userID)
	ret0, _ := ret[0].(model.JournalEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJournalEntry indicates an expected call of GetJournalEntry.
func (mr *MockJournalServiceMockRecorder) GetJournalEntry(ctx, entryID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJournalEntry", reflect.TypeOf((*MockJournalService)(nil).GetJournalEntry), ctx, entryID, userID)
}

// ListJournalEntries mocks base method.
func (m *MockJournalService) ListJournalEntries(ctx context.Context, userID uuid.UUID) ([]model.JournalEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListJournalEntries", ctx, userID)
	ret0, _ := ret[0].([]model.JournalEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListJournalEntries indicates an expected call of ListJournalEntries.
func (mr *MockJournalServiceMockRecorder) ListJournalEntries(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListJournalEntries", reflect.TypeOf((*MockJournalService)(nil).ListJournalEntries), ctx, userID)
}

// UpdateJournalEntry mocks base method.
func (m *MockJournalService) UpdateJournalEntry(ctx context.Context, entryID, userID uuid.UUID, content string, version int32) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateJournalEntry", ctx, entryID, userID, content, version)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateJournalEntry indicates an expected call of UpdateJournalEntry.
func (mr *MockJournalServiceMockRecorder) UpdateJournalEntry(ctx, entryID, userID, content, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateJournalEntry", reflect.TypeOf((*MockJournalService)(nil).UpdateJournalEntry), ctx, entryID, userID, content, version)
}
